import json
import numpy as np
import matplotlib.pyplot as plt


def calculate_population_restored(recovery_order, network_data, population_data):
    """
    Calculate cumulative population restored after each recovery step.

    :param recovery_order: List of nodes in the order of recovery
    :param network_data: Network data containing nodes and their service areas
    :param population_data: Population data with population counts for each area
    :return: List of cumulative population restored after each step
    """
    restored_areas = set()
    cumulative_population = []

    for node in recovery_order:
        # Get the service areas of the current node
        for n in network_data["nodes"]:
            if n["Code"] == node and n.get("Service Area"):
                areas = n["Service Area"].split(',')
                for area in areas:
                    restored_areas.add(area)
        # Calculate cumulative population after restoring this node
        current_population = sum(
            data["Population"] for data in population_data if data["Id"] in restored_areas
        )
        cumulative_population.append(current_population)

    return cumulative_population


def calculate_recovery_area(steps, populations):
    """
    Calculate the area under the recovery population curve using the trapezoidal rule.

    :param steps: List of recovery steps (integers)
    :param populations: List of cumulative populations at each step
    :return: Area under the recovery curve
    """
    # Calculate the area using the trapezoidal rule
    area = np.trapezoid(populations, steps)
    return area


def during_recovery_assessment_of_betweenness_based_recovery_order(global_json_path):
    """
    Evaluate network recovery resilience based on population data.
    Instead of recalculating the recovery order, it reads the recovery order from the result of the first step.

    :param global_json_path: Path to the global data JSON file
    :return: Area under the recovery population curve as the evaluation metric
    """
    # Load global data file to get network, population, and recovery strategy file paths
    with open(global_json_path, 'r') as file:
        file_paths = json.load(file)
        recovery_strategy_path = file_paths.get('recovery_order_determined_based_on_betweenness')
        network_file = file_paths.get('interdependent_critical_infrastructures_networks')
        population_file = file_paths.get('population_data')

    if not recovery_strategy_path:
        print("No recovery strategy file found in Global_Data.json.")
        return

    # Load the recovery order from the file generated by the first code
    with open(recovery_strategy_path, 'r') as file:
        recovery_result = json.load(file)
    recovery_order = recovery_result.get('recovery_order', [])
    if not recovery_order:
        print("Error: Recovery order is empty in the recovery strategy file.")
        return

    # Load network data
    with open(network_file, 'r') as file:
        network_data = json.load(file)

    # Load population data
    with open(population_file, 'r') as file:
        population_data = json.load(file)

    # Calculate cumulative population restored after each recovery step
    cumulative_population = calculate_population_restored(recovery_order, network_data, population_data)

    # Define recovery steps
    steps = list(range(1, len(recovery_order) + 1))
    # Calculate the area under the recovery curve
    recovery_area = calculate_recovery_area(steps, cumulative_population)

    plt.figure(figsize=(8, 5))
    plt.plot(steps, cumulative_population, marker='o', linestyle='-')
    plt.fill_between(steps, cumulative_population, alpha=0.3)
    plt.xlabel('Recovery Step', fontsize=12)
    plt.ylabel('Cumulative Population Restored', fontsize=12)
    plt.title(f'Network Recovery Population Curve\nArea = {recovery_area:.2f}', fontsize=14)
    plt.grid(True, linestyle='--', linewidth=0.5)
    plt.tight_layout()
    plt.show(block=False)
    plt.pause(2)
    plt.close()

    # Save recovery order and evaluation results to a JSON file
    result = {
        'recovery_order': recovery_order,  # Recovery order based on the first strategy result
        'number_of_nodes': len(recovery_order),
        'cumulative_population_restored': cumulative_population,
        'overall_network_recovery_evaluation': recovery_area  # Area under the recovery curve
    }

    output_json_path = 'during_recovery_assessment_of_betweenness_based_recovery_order.json'
    with open(output_json_path, 'w') as outfile:
        json.dump(result, outfile, indent=4)

    # Update the Global_Data.json file with the new recovery strategy result path
    file_paths['during_recovery_assessment_of_betweenness_based_recovery_order'] = output_json_path
    with open(global_json_path, 'w') as file:
        json.dump(file_paths, file, indent=4)

    print("Global_Data.json updated with recovery strategy result path.")

    return recovery_area


# Usage example
global_json_path = 'Global_Data.json'
during_recovery_assessment_of_betweenness_based_recovery_order(global_json_path)
